---
- hosts: all
  vars:
    GSERVER: 'gserver'
    #GSERVER_IP: 10.132.0.XX
  tasks:
    - name: Debian - install glusterfs client
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        package: glusterfs-client
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: delete old /etc/hosts entries
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '{{ GSERVER }}'

    - name: adding gluster server to /etc/hosts
      become: yes
      lineinfile:
        path: /etc/hosts
        regexp: '^{{ GSERVER_IP }}'
        line: '{{ GSERVER_IP }}    {{ GSERVER }}'

- hosts: gluster
  become: yes
  tasks:
    - name: Debian - install glusterfs server
      tags: gluster
      when: ansible_os_family == "Debian"
      apt:
        package: glusterfs-server
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: Configuring gluster server
      tags: gluster
      shell: "{{ item}}"
      loop:
        - 'wget https://raw.githubusercontent.com/gluster/glusterfs/master/extras/command-completion/gluster.bash -P /etc/bash_completion.d'

    - name: Configuring gluster server
      tags: example
      when: false
      shell: "{{ item}}"
      loop:
        - 'sed -i "s|^127.0.0.1.*|& $GSERVER|m" /etc/hosts'
        - 'mkdir -p $GBRICK'
        - 'gluster volume create $GVOLUME $GSERVER:$GBRICK force'
        - 'gluster volume start $GVOLUME'
        - 'echo "This is a GLUSTERFS test" > $GBRICK/index.html'
      environment:
        GBRICK: '/data/k8'
        GVOLUME: 'gfs'
        GSERVER: 'gserver'

# test: sudo mkdir -p /data/k8 && sudo mount -t glusterfs gserver:/gfs /data/k8
