---
- hosts:
    - masters
  tasks:
    - name: install k8s tools
      shell: "{{ item}}"
      loop:
        - "sudo curl -L https://github.com/kubernetes/kompose/releases/download/v1.16.0/kompose-linux-amd64 -o /usr/local/bin/kompose"
        - "sudo chmod +x /usr/local/bin/kompose"
        - "sudo curl -L https://github.com/kubernetes-sigs/kustomize/releases/download/v1.0.8/kustomize_1.0.8_linux_amd64 -o /usr/local/bin/kustomize"
        - "sudo chmod +x /usr/local/bin/kustomize"
        - "curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash"
