---
- hosts:
    - haproxy
  tasks:
    - name: deploy haproxy to instances
      tags:
        - git
      become: yes
      git:
        repo: "{{ item.git_repo }}"
        dest: "{{ item.git_dest }}"
        version: "{{ item.git_version | default('HEAD') }}"
        clone: yes
        update: yes
        accept_hostkey: yes
        force: yes
      loop:
        - { git_repo: 'https://github.com/carlessanagustin/docker_haproxy.git', git_dest: '/opt/haproxy', git_version: 'HEAD' }
