---
- name: "Install back up & restore Heptio Ark tool"
  hosts:
    - masters
  vars:
    INSTALL_DIR: ark-install
  tasks:
    - name: create ark installation path
      tags:
        - ark
      file:
        path: "{{ INSTALL_DIR }}"
        state: directory
        mode: 0775

    - name: "Installing the Ark Client"
      tags:
        - ark
        - client
      shell: "{{ item}}"
      args:
        chdir: "{{ INSTALL_DIR }}"
      loop:
        - "wget https://github.com/heptio/ark/releases/download/v0.10.0/ark-v0.10.0-linux-amd64.tar.gz"
        - "tar zxvf ark-v0.10.0-linux-amd64.tar.gz"
        - "sudo mv -f ark /usr/local/bin"
        - "sudo chown root:root /usr/local/bin/ark"
        - "grep -q -F 'source <(ark completion bash)' ~/.bashrc || echo 'source <(ark completion bash)' >> ~/.bashrc"
        - "rm -f ark-v0.10.0-linux-amd64.tar.gz"

    - name: "Installing and Configuring the Ark Server"
      tags:
        - ark
        - server
      shell: "{{ item}}"
      args:
        chdir: "{{ INSTALL_DIR }}"
      loop:
        - "git clone https://github.com/heptio/ark.git"
        # TODO: link
