---
- hosts: masters
  name: Setup k8s worker node
  gather_facts: false
  tasks:
    - name: get k8s join command
      tags:
        - worker
        - token
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set fact for join command
      tags:
        - worker
        - token
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  gather_facts: false
  vars:
    UNJOIN: false
  tasks:
    - name: unjoin k8s cluster
      when: UNJOIN
      tags:
        - worker
        - unjoin
      shell: "{{ item }}"
      loop:
        - "sudo systemctl stop kubelet.service"
        - "sudo rm -f /etc/kubernetes/pki/ca.crt"
        - "sudo rm -f /etc/kubernetes/kubelet.conf"
        - "sudo rm -f /etc/kubernetes/bootstrap-kubelet.conf"

    - name: join k8s cluster
      tags:
        - worker
        - join
      shell: "{{ item }}"
      loop:
        - "sudo modprobe -- ip_vs"
        - "sudo modprobe -- ip_vs_rr"
        - "sudo modprobe -- ip_vs_wrr"
        - "sudo modprobe -- ip_vs_sh"
        - "sudo {{ hostvars['master1'].join_command }} >> $HOME/node_joined.txt"
        - "sleep 10"
