# more: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network

---
- hosts: masters
  vars:
    # pod_network: flannel (untested) | calico (untested) | weave
    pod_network: weave
    # api_advertise: '--apiserver-advertise-address=10.132.0.14'
  tasks:
    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      when: pod_network == "flannel" or pod_network == "weave"
      become: yes
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present

    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      when: pod_network == "flannel" or pod_network == "weave"
      become: yes
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: weave - setting pod network cidr
      when: pod_network == "weave"
      become: yes
      shell: "kubeadm init {{ api_advertise | default ('') }} >> $HOME/cluster_initialized.txt"

    - name: flannel - setting pod network cidr
      when: pod_network == "flannel"
      become: yes
      shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 {{ api_advertise | default ('') }} >> $HOME/cluster_initialized.txt"

    - name: calico - setting pod network cidr
      when: pod_network == "calico"
      become: yes
      shell: "kubeadm init --pod-network-cidr=192.168.0.0/16 {{ api_advertise | default ('') }} >> $HOME/cluster_initialized.txt"

    - name: setting up user environment
      shell: "{{ item }}"
      tags:
        - user_env
      loop:
        - "mkdir -p $HOME/.kube"
        - "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
        - "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

    - name: flannel - deploy a pod network to the cluster
      when: pod_network == "flannel"
      shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml >> $HOME/pod_network_setup.txt"

    - name: calico - deploy a pod network to the cluster
      when: pod_network == "calico"
      shell: "{{ item }}"
      loop:
        - "kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml  >> $HOME/pod_network_setup.txt"
        - "kubectl apply -f https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml  >> $HOME/pod_network_setup.txt"

    - name: weave - deploy a pod network to the cluster
      when: pod_network == "weave"
      shell: "kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')  >> $HOME/pod_network_setup.txt"

    - name: check master status
      pause:
        seconds: 15

    - name: run kubectl get pods --all-namespaces
      shell: "kubectl get pods --all-namespaces"
      register: my_pods

    - name: show pods
      debug:
        var: my_pods
